# Criação de um dicionário onde as chaves são códigos DDD e os valores são as regiões correspondentes
ddd_brasil = {
    "11": "São Paulo e região metropolitana",
    "12": "São José dos Campos e Vale do Paraíba (SP)",
    "13": "Baixada Santista (SP)",
    "14": "Bauru e região (SP)",
    "15": "Sorocaba e região (SP)",
    "16": "Ribeirão Preto e região (SP)",
    "17": "São José do Rio Preto e região (SP)",
    "18": "Presidente Prudente e região (SP)",
    "19": "Campinas e região (SP)",
    "21": "Rio de Janeiro e região metropolitana",
    "22": "Campos dos Goytacazes e região (RJ)",
    "24": "Volta Redonda e região (RJ)",
    "27": "Vitória e região metropolitana (ES)",
    "28": "Cachoeiro de Itapemirim e região (ES)",
    "31": "Belo Horizonte e região metropolitana (MG)",
    "32": "Juiz de Fora e região (MG)",
    "33": "Governador Valadares e região (MG)",
    "34": "Uberlândia e região (MG)",
    "35": "Poços de Caldas e região (MG)",
    "37": "Divinópolis e região (MG)",
    "38": "Montes Claros e região (MG)",
    "41": "Curitiba e região metropolitana (PR)",
    "42": "Ponta Grossa e região (PR)",
    "43": "Londrina e região (PR)",
    "44": "Maringá e região (PR)",
    "45": "Foz do Iguaçu e região (PR)",
    "46": "Francisco Beltrão e região (PR)",
    "47": "Joinville e região (SC)",
    "48": "Florianópolis e região metropolitana (SC)",
    "49": "Chapecó e região (SC)",
    "51": "Porto Alegre e região metropolitana (RS)",
    "53": "Pelotas e região (RS)",
    "54": "Caxias do Sul e região (RS)",
    "55": "Santa Maria e região (RS)",
    "61": "Distrito Federal e região (DF)",
    "62": "Goiânia e região metropolitana (GO)",
    "63": "Palmas e região (TO)",
    "64": "Rio Verde e região (GO)",
    "65": "Cuiabá e região metropolitana (MT)",
    "66": "Rondonópolis e região (MT)",
    "67": "Campo Grande e região metropolitana (MS)",
    "68": "Rio Branco e região (AC)",
    "69": "Porto Velho e região (RO)",
    "71": "Salvador e região metropolitana (BA)",
    "73": "Ilhéus e região (BA)",
    "74": "Juazeiro e região (BA)",
    "75": "Feira de Santana e região (BA)",
    "77": "Barreiras e região (BA)",
    "79": "Aracaju e região metropolitana (SE)",
    "81": "Recife e região metropolitana (PE)",
    "82": "Maceió e região metropolitana (AL)",
    "83": "João Pessoa e região metropolitana (PB)",
    "84": "Natal e região metropolitana (RN)",
    "85": "Fortaleza e região metropolitana (CE)",
    "86": "Teresina e região metropolitana (PI)",
    "87": "Petrolina e região (PE)",
    "88": "Juazeiro do Norte e região (CE)",
    "89": "Picos e região (PI)",
    "91": "Belém e região metropolitana (PA)",
    "92": "Manaus e região metropolitana (AM)",
    "93": "Santarém e região (PA)",
    "94": "Marabá e região (PA)",
    "95": "Boa Vista e região (RR)",
    "96": "Macapá e região (AP)",
    "97": "Coari e região (AM)",
    "98": "São Luís e região metropolitana (MA)",
    "99": "Imperatriz e região (MA)"
}

# Loop para iterar sobre cada item no dicionário ddd_brasil
for ddd, regiao in ddd_brasil.items():
    # Para cada par chave-valor (ddd, regiao), imprime uma string formatada
    # onde {ddd} é o código DDD e {regiao} é a região correspondente
    print(f"{ddd}: {regiao}")
